spring.application.name=Pedidos
server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# H2 DATABASE
spring.datasource.url=jdbc:h2:mem:pedidos
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#http://localhost:8081/h2-console

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true